// components/QueueSelector.vue
<script setup lang="ts">
const { queues, open } = defineProps<{
  open: boolean
  queues: Queue[]
}>()

const isLoading = ref(false)
const selectedQueue = ref<Queue | undefined>()
// const router = useRouter()

const handleSubmit = async () => {
  if (!selectedQueue.value) return
  isLoading.value = true
  // await enqueue(selectedQueue)
  // router.refresh()
  isLoading.value = false
}
</script>

<template>
  <a-card
    title="Redeliste wählen"
  >
    <template #actions>
      <a-row key="enqueue" style="padding: 0 12px">
        <a-col :span="24">
          <a-button
            type="primary"
            :disabled="selectedQueue === undefined || !open"
            block
            size="large"
            :loading="isLoading"
            @click="handleSubmit"
          >
            {{ open ? 'Redebeitrag anmelden' : 'Redelisten sind geschlossen' }}
          </a-button>
        </a-col>
      </a-row>
    </template>
    <a-list
      style="width: 300px"
      :data-source="queues"
    >
      <template #renderItem="{ item: queue }">
        <a-list-item
          class="queue-item"
          :class="queue.id === selectedQueue?.id && 'selected'"
          @click="() => selectedQueue = queue"
        >
          <a-radio
            :checked="queue.id === selectedQueue?.id"
            @change="selectedQueue = queue"
          >
            <a-typography>{{ queue.name }}</a-typography>
          </a-radio>
        </a-list-item>
      </template>
    </a-list>
  </a-card>
</template>

<style scoped>
.queue-item {
  display: flex;
  align-items: start;
  background-color: transparent;
  border-color: transparent;
  border-width: 2px;
  border-style: solid;
  cursor: pointer;
  padding-left: 10px;
  padding-right: 10px;
  border-radius: 5px;
}

.queue-item.selected {
  background-color: #e6f7ff;
  border-color: #1890ff;
}

/* Counteracts border-block-end styling by Antd - without it the last item would miss the bottom border */

.queue-item:last-of-type {
  border-block-end: 2px solid transparent;
}

.queue-item.selected:last-of-type {
  border-block-end-color: #1890ff;
}
</style>

// src/components/QueueSelector.tsx
"use client"

import { enqueue } from "@/app/actions";
import { Queue } from "@prisma/client";
import { Button, Card, Col, List, Radio, Row, Typography } from "antd";
import { useRouter } from "next/navigation";
import { useState } from "react";

export default function QueueSelector({ queues, open }: { queues: Queue[], open: boolean }) {
  const [isLoading, setIsLoading] = useState(false)
  const [selectedQueue, setSelectedQueue] = useState<Queue | undefined>()
  const router = useRouter()

  const handleSubmit = async () => {
    if (!selectedQueue) return
    setIsLoading(true)
    await enqueue(selectedQueue)
    router.refresh()
    setIsLoading(false)
  }

  return (
    <Card
      title="Redeliste wählen"
      actions={[
        <Row key="enqueue" style={{ padding: "0 12px" }}>
          <Col span={24}>
            <Button
              type="primary"
              disabled={selectedQueue === undefined || !open}
              block
              size="large"
              loading={isLoading}
              onClick={handleSubmit}
            >
              {open ? 'Redebeitrag anmelden' : 'Redelisten sind geschlossen'}
            </Button>
          </Col>
        </Row>
      ]}>
      <List
        style={{ width: 300 }}
        dataSource={queues}
        renderItem={(queue) => (
          <List.Item
            onClick={() => setSelectedQueue(queue)}
            style={{
              display: 'flex',
              alignItems: 'start',
              backgroundColor: queue.id === selectedQueue?.id ? '#e6f7ff' : 'transparent',
              borderColor: queue.id === selectedQueue?.id ? '#1890ff' : 'transparent',
              borderWidth: 2,
              borderStyle: "solid",
              cursor: 'pointer',
              paddingLeft: 10,
              paddingRight: 10,
              borderRadius: 5,
            }}
          >
            <Radio
              checked={queue.id === selectedQueue?.id}
              onChange={() => setSelectedQueue(queue)}
            >
              <Typography>{queue.name}</Typography>
            </Radio>
          </List.Item>
        )}
      />
    </Card>
  )
}
